
// console.log("test");
// var sophis = sophis || {};
// var videoNode = document.getElementsByTagName("VIDEO");

// // var xhr = new XMLHttpRequest();

// // xhr.open("GET", "https://youtube.com/get_video_info?video_id=", false);
// // xhr.send();

// var result = xhr.responseText;

chrome.tabs.query({active: true, currentWindow: true}, function(tabs) {
	var searchText = document.getElementById('searchTerm');
	var url = tabs[0].url;
 	var vid_regex = /v=(.*)/;
 	var match = url.match(vid_regex);
 	var vid = match[1];
 	// console.log(vid);
 	var sophis = sophis || {};
	var videoNode = document.getElementsByTagName("VIDEO");

	var xhr = new XMLHttpRequest();

	xhr.open("GET", "https://youtube.com/get_video_info?video_id=" + vid, true);
	xhr.onreadystatechange = function() {
  	if (xhr.readyState == 4) {
  			var result = xhr.responseText;
			var decoded = decodeURIComponent(result);

			// console.log(decoded);

			if (decoded.includes('captionTracks')){
				

				// var defaultCaptionTrackregex = /"defaultCaptionTrackIndex":(\d)/;
				// var defaultCaptionTrackIndex = decoded.match(defaultCaptionTrackregex)[1];
  				
				var regex = /({"captionTracks":.*isTranslatable":(true|false)}])/;
  				var matched = decoded.match(regex);
  				// console.log(matched)
  				if (matched.length > 0){
  					var parsedCaptionTracks = JSON.parse(matched[0] + "}");
  					var selectedCaptionTrack;
  					//prioritize non-autogenerated cc over autogenerated cc
  					for (i = 0; i <parsedCaptionTracks["captionTracks"].length; i++){
  						if(parsedCaptionTracks["captionTracks"][i]["vssId"] == '.en'){
  							selectedCaptionTrack = parsedCaptionTracks["captionTracks"][i]
  						}
  						if (!selectedCaptionTrack && parsedCaptionTracks["captionTracks"][i]["vssId"] == 'a.en'){
  							selectedCaptionTrack = parsedCaptionTracks["captionTracks"][i]
  						}

  					}
  					// var selectedCaptionTrack = parsedCaptionTracks["captionTracks"][Number(defaultCaptionTrackIndex)];
  					// console.log(selectedCaptionTrack);
  					var captionURL =  selectedCaptionTrack["baseUrl"]


  					xhr.open("GET", captionURL, true);
  					xhr.onreadystatechange = function(){
  						var captions = xhr.responseText;
  						// console.log(decodeURIComponent(captions))
  						var replaced = captions.replace('<?xml version="1.0" encoding="utf-8" ?><transcript>', '')
  						.replace(/&lt;.*?&gt;/g, '')
  						.replace(/&amp;#39;/g, "'");
  						
  						var searchTexRegex;
  						
  						searchText.addEventListener("keyup", function(event) {
  						// Cancel the default action, if needed
  							event.preventDefault();
  						// Number 13 is the "Enter" key on the keyboard
  							if (event.keyCode === 13) {
  								
  								var text = searchText.value;
  								if (!searchTexRegex) searchTexRegex =  new RegExp('start="(\\d+.\\d+)"(?:(?!<).)*'+ text, 'gmi');
  								// console.log(text);	
  								var matchedCaptions = searchTexRegex.exec(replaced);
  								// console.log(matchedCaptions);
  								var videoLocaion = matchedCaptions[1];
  								chrome.tabs.executeScript(
          							tabs[0].id,
          							{code: 'document.getElementsByTagName("VIDEO")[0].currentTime='+ videoLocaion+ ';'});

  							} else {
  								searchTexRegex = null;	
  							}
  						});
  					}
  					xhr.send();
  				}  			
			}
  		}
  	}
	xhr.send();


});